name: Build Rocket.Chat Custom Docker Image

on:
  push:
    branches:
      - main
      - master
      - develop
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:  # Allow manual trigger

env:
  IMAGE_NAME: rocketchat-custom
  IMAGE_TAG: jenkins

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      

    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ env.IMAGE_TAG }}
          type=raw,value=${{ env.IMAGE_TAG }}-{{sha}}
          type=raw,value=${{ env.IMAGE_TAG }}-{{date 'YYYYMMDD'}}
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
        
    - name: Test Docker image
      run: |
        # Run basic container test
        docker run --rm --name test-rocketchat \
          -e MONGO_URL=mongodb://localhost:27017/meteor \
          -d ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        
        # Wait a few seconds for container to start
        sleep 10
        
        # Check if container is running
        if docker ps | grep -q test-rocketchat; then
          echo "✅ Container started successfully"
          docker logs test-rocketchat
          docker stop test-rocketchat
        else
          echo "❌ Container failed to start"
          docker logs test-rocketchat 2>/dev/null || true
          exit 1
        fi
    
    - name: Push to Docker Hub
      if: false  # Disabled - only building, not pushing
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
    
    - name: Save Docker image as artifact
      run: |
        docker save ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} | gzip > rocketchat-custom-jenkins.tar.gz
        
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: rocketchat-custom-jenkins-image
        path: rocketchat-custom-jenkins.tar.gz
        retention-days: 7
        
    - name: Display image info
      run: |
        echo "🐳 Docker Image Built Successfully!"
        echo "Image Name: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
        echo "Image Size: $(docker images ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --format 'table {{.Size}}')"
        echo "Build Date: $(date)"
        docker images ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
