name: Build Rocket.Chat Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        run: docker build -t my-custom-rocketchat .
      
      - name: List Docker images
        run: docker images
