name: Build Rocket.Chat Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Show files in workspace
        run: |
          pwd
          ls -la

      - name: Build Docker image
        run: docker build -t my-custom-rocketchat .
