name: Build Rocket.Chat Docker Image

on:
  push:
    branches:
      - test1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-custom-rocketchat .

      - name: Save Docker image as tar
        run: docker save my-custom-rocketchat -o rocketchat.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rocketchat-image
          path: rocketchat.tar
